
-- Xóa cơ sở dữ liệu nếu tồn tại
-- DROP DATABASE IF EXISTS bookstoreDB;
-- Tạo cơ sở dữ liệu
-- CREATE DATABASE bookstoreDB;
USE bookstoreDB;

CREATE TABLE Roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL
);

-- Tạo bảng Users lưu thông tin người dùng
CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    role_id INT NOT NULL DEFAULT 2,
    status INT NOT NULL DEFAULT 1, -- Thêm cột status
    FOREIGN KEY (role_id) REFERENCES Roles(id)
);

-- Tạo bảng Books lưu thông tin sách
CREATE TABLE Books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    ImageURL VARCHAR(500),
    stock_quantity INT NOT NULL,
    book_description TEXT NOT NULL,
    status TINYINT DEFAULT 1  -- Thêm cột status với giá trị mặc định
);

-- Tạo bảng Orders lưu thông tin đơn hàng
CREATE TABLE Orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,  -- Liên kết với bảng Users
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_price DECIMAL(10,2) NOT NULL,
    status ENUM('Đang xử lý', 'Đã giao', 'Đã hủy') DEFAULT 'Đang xử lý',  -- Trạng thái đơn hàng
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

-- Tạo bảng OrderDetails lưu chi tiết đơn hàng
CREATE TABLE Order_Details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    book_id INT NOT NULL,
    quantity INT default 1,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,  -- Bỏ UNIQUE để có thể trùng email
    phone_number VARCHAR(20) NOT NULL,
    province_city TEXT NOT NULL,
    district TEXT NOT NULL,
    ward TEXT NOT NULL,
    street TEXT NOT NULL,
    note_order TEXT,
    total_price DECIMAL(10,2) NOT NULL,
    payment_method varchar(255) NOT NULL,
    order_status ENUM('Đang xử lý', 'Đã xử lý') NOT NULL
);


-- Thêm dữ liệu vào bảng Users
INSERT INTO Users(username, password, email, role_id, status) VALUES
('admin', '123', 'admin@example.com', 1, 1),
('user1', '123', 'john.doe@example.com', 2, 1),
('user2', '123', 'jane.smith@example.com', 2, 1),
('user3', '123', 'peter.parker@example.com', 2, 1);

-- Thêm dữ liệu vào bảng Roles
INSERT INTO Roles(id, role_name) VALUES
(1, 'Admin'),
(2, 'User');

-- Thêm dữ liệu vào bảng Orders
INSERT INTO Orders(user_id, total_price, status) VALUES
(1, 250.000, 'Đang xử lý'),
(2, 420.000, 'Đã giao'),
(3, 180.000, 'Đang xử lý'),
(4, 300.000, 'Đã hủy');

-- Thêm dữ liệu vào bảng Order_Details
INSERT INTO Order_Details(book_id, full_name, email, phone_number, province_city, district, ward, street, note_order, total_price, payment_method, order_status) VALUES
( 3,  'Nguyễn Văn A', 'admin@example.com', '0901234567', 'Hà Nội', 'Hoàn Kiếm', 'Hàng Trống', '45 Lý Thường Kiệt', 'Giao hàng giờ hành chính', 250.000, 'Thanh toán khi nhận hàng', 'Đang xử lý'),
( 7, 'Trần Thị B', 'admin@example.com', '0987654321', 'TP. Hồ Chí Minh', 'Quận 1', 'Bến Nghé', '22 Nguyễn Huệ', 'Gọi trước khi giao', 250.000, 'Chuyển khoản qua internet banking', 'Đã xử lý'),
( 2, 'Lê Văn C', 'admin@example.com', '0912345678', 'Đà Nẵng', 'Hải Châu', 'Hòa Thuận Đông', '88 Trần Phú', NULL, 250.000, 'Thanh toán khi nhận hàng', 'Đang xử lý'),
( 4, 'Phạm Minh D', 'admin@example.com', '0934567890', 'Cần Thơ', 'Ninh Kiều', 'An Bình', '12 Võ Văn Kiệt', 'Không gọi điện', 250.000, 'Chuyển khoản qua internet banking', 'Đã xử lý');

insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Làm Bạn Với Bầu Trời","Nguyễn Nhật Ánh",88.000,"https://pibook.vn/upload/products/2020_04_13_11_18_55_1-390x510.jpg",10,"Một câu chuyện giản dị, chứa đầy bất ngờ cho tới trang cuối cùng. Và đẹp lộng lẫy, vì lòng vị tha và tình yêu thương, khiến mắt rưng rưng vì một nỗi mừng vui hân hoan. Cuốn sách như một đốm lửa thắp lên lòng khát khao sống tốt trên đời.");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Mắt Biếc","Nguyễn Nhật Ánh",77.000,"https://pibook.vn/upload/products/67d0ef3d3fc8897213c9a1f84ee561e1.jpg",10,"Một tác phẩm được nhiều người bình chọn là hay nhất của nhà văn này. Một tác phẩm đang được dịch và giới thiệu tại Nhật Bản (theo thông tin từ các báo)… Bởi sự trong sáng của một tình cảm, bởi cái kết thúc rất, rất buồn khi suốt câu chuyện vẫn là những điều vui, buồn lẫn lộn (cái kết thúc không như mong đợi của mọi người). Cũng bởi, mắt biếc… năm xưa nay đâu (theo lời một bài hát).");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Việt Nam Danh Tác - Số Đỏ","Vũ Trọng Phụng",60.000,"https://pibook.vn/upload/product-slide/07aef25a3e7d7b6e78f5184dbe3c842f.jpg",10,"Số Đỏ là một tiểu thuyết văn học của nhà văn Vũ Trọng Phụng, đăng ở Hà Nội báo từ số 40 ngày 7 tháng 10 năm 1936 và được in thành sách lần đầu vào năm 1938. ");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Trúng Số Độc Đắc","Vũ Trọng Phụng",38.000,"https://pibook.vn/upload/product-slide/tr%C3%BAngo.jpg",10,"Tiểu thuyết Trúng số độc đắc được Vũ Trọng Phụng viết năm 1938, lúc nhà văn 26 tuổi. Trúng số độc đắc có đầy đủ mọi yếu tố của một “tiểu thuyết luận đề”. Tác giả đã tận dụng mọi cơ hội để phát biểu những suy ngẫm, quan niệm của mình về con người, về cuộc sống. ");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Số Đỏ","Vũ Trọng Phụng",45.000,"https://pibook.vn/upload/product-slide/so-do-1.png",10,"Số Đỏ - cuốn sách nằm trong bộ Tủ sách Văn học trong nhà trường được Nhà xuất bản Kim Đồng tổ chức biên soạn nhằm giúp các bạn học sinh có một nền tảng kiến thức văn học phong phú, vững vàng. Bộ sách sẽ lần lượt giới thiệu tác phẩm của các tác giả thuộc nhiều trào lưu, thể loại, thời kì...");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Làm Đĩ","Vũ Trọng Phụng",38.500,"https://pibook.vn/upload/product-slide/lam-di-dinh-ti.png",10,"Trong văn học Việt Nam, Vũ Trọng Phụng luôn được biết đến như một nhà văn hiện thực xuất sắc, với những tác phẩm khắc họa sâu sắc và chân thực những góc tối của xã hội. Và 'Làm Đĩ', tiểu thuyết mới nhất được Đinh Tị phát hành, tiếp tục là một minh chứng hùng hồn cho tài năng và tâm huyết của ông trong việc phơi bày những bất công và thành kiến xã hội.");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Sống Mòn","Nam Cao",76.300,"https://pibook.vn/upload/product-slide/songmonnamcao.jpg",10,"Sống Mòn (Nhã Nam) là cuốn truyện ngắn, một tác phẩm mang đầy chất hiện thực và tự sự, đôi lúc cảm tưởng như đây là cuốn nhật ký cho một quãng đời của tác giả. ");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Chí Phèo","Nam Cao",35.300,"https://pibook.vn/upload/product-slide/chipheo-namcao%20-bia1_.u547.d20160404.t145748.jpg",10,"Chí Phèo (Minh Long) là tập truyện ngắn tái hiện bức tranh chân thực nông thôn Việt Nam trước 1945, nghèo đói, xơ xác trên con đường phá sản, bần cùng, hết sức thê thảm, người nông dân bị đẩy vào con đường tha hóa, lưu manh hóa. ");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Tuyển Tập Nam Cao","Nam Cao",35.300,"https://pibook.vn/upload/product-slide/nam_cao_900x900_a3239419db1b411fb23c070dca20f5dc_master.jpeg",10,"Tuyển Tập Nam Cao là tập hợp những truyện ngắn xuất sắc của nhà văn tài hoa này.");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Nàng Mona Lisa Cuối Cùng","Jonathan Santlofer",118.300,"https://pibook.vn/upload/product-slide/nang-mona-lisa-cuoi-cung-15012025.jpg",10,"Nàng Mona Lisa Cuối Cùng - Bí Ẩn Vụ Trộm Động Trời.");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Utopia - Địa Đàng Trần Gian","Thomas More",49.000 ,"https://pibook.vn/upload/product-slide/utopia-dia-dang-tran-gian-15012025.jpg",10,"Utopia - Địa Đàng Trần Gian: Hành Trình Đến Xứ Sở Lý Tưởng");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Hẹn Nhau Tháng Tám","Gabriel García Márquez",97.300 ,"https://pibook.vn/upload/product-slide/hen-nhau-thang-tam-24122024.jpg",10,"Hẹn Nhau Tháng Tám - Giảm 30% | Tiểu Thuyết Lãng Mạn | Pibook.vn - Khúc Bolero Về Tình Yêu Và Bí Ẩn");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Những Đứa Trẻ Thượng Lưu","Ngô Hiểu Lạc",94.500 ,"https://pibook.vn/upload/product-slide/nhung-dua-tre-thuong-luu-02012025.jpg",10,"Những Đứa Trẻ Thượng Lưu - Bước Vào Thế Giới Ảo Mộng");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Vũ Khúc Đoạn Tình","Stephanie Garber",118.300 ,"https://pibook.vn/upload/product-slide/vu-khuc-doan-tinh-19122024.jpg",10,"Vũ Khúc Đoạn Tình - Lời Nguyền Chết Chóc Và Mối Tình Mong Manh");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Ở Xứ Tự Do","V. S. Naipaul",117.600 ,"https://pibook.vn/upload/product-slide/o-xu-tu-do-20122024.jpg",10,"Ở Xứ Tự Do - Những Mảnh Đời Lưu Lạc");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Bản Chất Của Người","Han Kang",90.300,"https://pibook.vn/upload/product-slide/ban-chat-cua-nguoi-06122024.jpg",10,"Bản Chất Của Người - Cuộc Đấu Tranh Nội Tâm Đầy Day Dứt");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Chuyện Hứa Tam Quan Bán Máu","Dư Hoa",117.600,"https://pibook.vn/upload/product-slide/chuyen-hua-tam-quan-ban-mau-25112024.jpg",10,"Chuyện Hứa Tam Quan Bán Máu - Cuộc Đời Đầy Xót Xa Giữa Biển Đời Bão Táp");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Charlie Thương Nhớ","N.D Gomes",72.250,"https://pibook.vn/upload/product-slide/charlie-thuong-nho-13112024.jpg",10,"Charlie Thương Nhớ - Nỗi Đau Và Sự Tha Thứ");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Bà Nội Găngxtơ Tái Xuất!","David Walliams",108.500,"https://pibook.vn/upload/product-slide/ba-noi-gangxto-tai-xuat-13112024.jpg",10,"Bà Nội Găngxtơ Tái Xuất! - Cuộc Phiêu Lưu Mới Kịch Tính");
insert into books(title, author, price, ImageURL, stock_quantity, book_description) VALUE ("Những Đứa Con Của Nửa Đêm","Salman Rushdie",168.000,"https://pibook.vn/upload/product-slide/nhung-dua-con-cua-nua-dem-02112024.jpg",10,"Những Đứa Con Của Nửa Đêm: Huyền Ảo, Đồ Sộ Và Kỳ Thú!");


INSERT INTO books (title, author, price, ImageURL, stock_quantity, book_description) VALUES
("Cho Tôi Xin Một Vé Đi Tuổi Thơ", "Nguyễn Nhật Ánh", 90.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974178866.jpg", 15, "Một hành trình trở về tuổi thơ đầy trong trẻo và hồn nhiên, nơi những trò nghịch ngợm, tình bạn chân thành và những rung động đầu đời được tái hiện sống động qua ngòi bút tài hoa của Nguyễn Nhật Ánh. Cuốn sách như một tấm vé đưa người đọc trở lại những ngày tháng vô tư, gợi lên ký ức ngọt ngào và cả những tiếc nuối về một thời đã xa."),
("Tôi Thấy Hoa Vàng Trên Cỏ Xanh", "Nguyễn Nhật Ánh", 120.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974157731.jpg", 20, "Tác phẩm kể về hành trình trưởng thành đầy cảm xúc của hai anh em Thiều và Tường trong khung cảnh làng quê Việt Nam yên bình. Qua những biến cố gia đình, tình thân và những rung động đầu đời, câu chuyện đan xen giữa niềm vui và nỗi buồn, khắc họa sâu sắc vẻ đẹp của tuổi thơ và những giá trị nhân văn giản dị nhưng thấm thía."),
("Cây Chuối Non Đi Giày Xanh", "Nguyễn Nhật Ánh", 95.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974189640.jpg", 8, "Một câu chuyện nhẹ nhàng, hài hước và ấm áp về tuổi thơ ở làng quê, nơi những ký ức về tình bạn, tình thân và những trò chơi trẻ thơ được tái hiện sống động. Với văn phong trong sáng và dí dỏm, Nguyễn Nhật Ánh mang đến một thế giới đầy màu sắc, nơi người đọc tìm thấy sự bình yên và những cảm xúc chân thật của tuổi hồn nhiên."),
("Nhật Ký Chú Bé Nhút Nhát", "Jeff Kinney", 75.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936066692258.jpg", 18, "Cuốn nhật ký hài hước của cậu bé Greg Heffley, một học sinh trung học nhút nhát nhưng đầy mưu mẹo. Qua từng trang sách, người đọc được chứng kiến những tình huống dở khóc dở cười trong cuộc sống học đường, từ những rắc rối với bạn bè, gia đình đến những kế hoạch ngớ ngẩn nhưng đáng yêu, khiến cuốn sách trở thành bạn đồng hành lý tưởng cho tuổi teen."),
("Totto-Chan Bên Cửa Sổ", "Kuroyanagi Tetsuko", 98.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590829.jpg", 14, "Câu chuyện cảm động về cô bé Totto-chan tinh nghịch và hành trình học tập tại Tomoe - một ngôi trường đặc biệt ở Nhật Bản. Qua những trải nghiệm độc đáo, cuốn sách không chỉ tái hiện tuổi thơ đầy sáng tạo mà còn truyền tải thông điệp sâu sắc về giáo dục bằng tình yêu thương, sự tôn trọng cá tính riêng của mỗi đứa trẻ."),
("Đắc Nhân Tâm", "Dale Carnegie", 86.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848520.jpg", 16, "Một trong những cuốn sách kỹ năng giao tiếp kinh điển nhất mọi thời đại, Đắc Nhân Tâm mang đến những bài học quý giá về cách đối nhân xử thế, xây dựng mối quan hệ và chinh phục lòng người. Với lối viết gần gũi và những ví dụ thực tiễn, Dale Carnegie không chỉ giúp người đọc cải thiện kỹ năng xã hội mà còn truyền cảm hứng để sống tích cực và thành công hơn."),
("Nhà Giả Kim", "Paulo Coelho", 79.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216727.jpg", 13, "Hành trình của chàng trai Santiago đi tìm kho báu ẩn giấu trong kim tự tháp Ai Cập là một câu chuyện đầy ý nghĩa về ước mơ, lòng kiên trì và sự khám phá bản thân. Với văn phong giàu triết lý và hình ảnh biểu tượng sâu sắc, Paulo Coelho đã tạo nên một tác phẩm truyền cảm hứng mạnh mẽ, khích lệ người đọc lắng nghe trái tim và theo đuổi đam mê của mình."),
("Harry Potter Và Hòn Đá Phù Thủy", "J.K. Rowling", 150.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177890.jpg", 17, "Phần đầu tiên trong loạt truyện nổi tiếng toàn cầu, cuốn sách mở ra thế giới phép thuật kỳ diệu của Harry Potter – cậu bé mồ côi khám phá ra thân phận phù thủy của mình. Với những cuộc phiêu lưu đầy kịch tính tại trường Hogwarts, tác phẩm không chỉ cuốn hút bởi sự tưởng tượng phong phú mà còn bởi tình bạn, lòng dũng cảm và những giá trị nhân văn sâu sắc."),
("Thiên Tài Bên Trái, Kẻ Điên Bên Phải", "Cao Minh", 125.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540421.jpg", 10, "Cuốn sách độc đáo khám phá ranh giới mong manh giữa thiên tài và kẻ điên qua những câu chuyện thực tế về các bệnh nhân tâm thần. Tác giả Cao Minh dẫn dắt người đọc vào thế giới nội tâm phức tạp, nơi những suy nghĩ dị thường lại chứa đựng sự sáng tạo đáng kinh ngạc, khiến người đọc không khỏi trăn trở về bản chất của con người."),
("Trên Đường Băng", "Tony Buổi Sáng", 92.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936066709123.jpg", 19, "Một cuốn sách đầy thực tế và dí dỏm dành cho người trẻ, Trên Đường Băng là tập hợp những bài học giá trị về kỹ năng sống, tư duy làm việc và cách chuẩn bị cho hành trình lập nghiệp. Với giọng văn gần gũi như một người bạn, Tony Buổi Sáng truyền động lực mạnh mẽ, khuyến khích thế hệ trẻ dấn thân và không ngừng học hỏi."),
("Cà Phê Cùng Tony", "Tony Buổi Sáng", 78.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936066709130.jpg", 14, "Tập hợp những tản văn hài hước, sâu cay nhưng không kém phần sâu sắc, Cà Phê Cùng Tony như một ly cà phê sáng giúp người đọc tỉnh táo và suy ngẫm về cuộc sống. Từ những câu chuyện đời thường đến những bài học ý nghĩa, cuốn sách truyền cảm hứng sống tích cực, tự tin và luôn hướng về phía trước."),
("Bí Mật Tư Duy Triệu Phú", "T. Harv Eker", 99.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848537.jpg", 11, "Cuốn sách tài chính nổi tiếng này hé lộ cách tư duy khác biệt của những người giàu có, đồng thời cung cấp những chiến lược thực tiễn để thay đổi thói quen tài chính cá nhân. T. Harv Eker không chỉ truyền đạt kiến thức mà còn khơi dậy niềm tin vào khả năng làm giàu, giúp người đọc từng bước xây dựng con đường đến sự thịnh vượng."),
("Dám Nghĩ Lớn", "David J. Schwartz", 105.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848544.jpg", 13, "Một tác phẩm truyền cảm hứng mạnh mẽ, Dám Nghĩ Lớn khuyến khích người đọc vượt qua nỗi sợ hãi và giới hạn bản thân để đạt được những thành công lớn lao. Với những lời khuyên thực tế và tư duy tích cực, David J. Schwartz giúp bạn thay đổi cách nhìn về tiềm năng của chính mình, từ đó dám mơ ước và hành động để biến giấc mơ thành hiện thực."),
("Hành Tinh Của Một Kẻ Nghĩ Nhiều", "Aki", 89.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540391.jpg", 12, "Tản văn nhẹ nhàng nhưng sâu lắng, cuốn sách là tiếng lòng của những người trẻ hay suy tư trong cuộc sống hiện đại. Aki dẫn dắt người đọc qua những cảm xúc phức tạp, những câu hỏi không lời đáp và cả những khoảnh khắc bình yên hiếm hoi, tạo nên một hành trình nội tâm đầy cảm hứng và đồng cảm."),
("Ông Già Và Biển Cả", "Ernest Hemingway", 68.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590959.jpg", 10, "Tác phẩm kinh điển của Hemingway kể về cuộc chiến đấu kiên cường của lão ngư dân Santiago với con cá kiếm khổng lồ giữa đại dương mênh mông. Qua ngòi bút giản dị nhưng sâu sắc, cuốn sách không chỉ ca ngợi ý chí bất khuất của con người mà còn gợi lên những suy ngẫm về sự cô đơn, lòng kiên nhẫn và khát vọng chiến thắng nghịch cảnh."),
("Chuyện Con Mèo Dạy Hải Âu Bay", "Luis Sepúlveda", 72.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216734.jpg", 15, "Một câu chuyện ấm áp và đầy ý nghĩa về tình bạn giữa chú mèo Zorba và cô hải âu con mồ côi. Với lời hứa dạy hải âu bay, chú mèo cùng bạn bè đã vượt qua mọi khó khăn để thực hiện trách nhiệm, mang đến bài học cảm động về lòng trung thành, sự hy sinh và tình yêu thương vượt qua ranh giới loài."),
("Kafka Bên Bờ Biển", "Haruki Murakami", 140.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216741.jpg", 11, "Tiểu thuyết kỳ ảo của Murakami kể về hành trình chạy trốn và tìm kiếm ý nghĩa cuộc sống của cậu bé Kafka Tamura và ông lão Nakata. Đan xen giữa thực và mộng, tác phẩm dẫn dắt người đọc vào một thế giới bí ẩn, nơi những câu hỏi về số phận, ký ức và tình yêu được đặt ra một cách đầy ám ảnh và sâu sắc."),
("Rừng Na Uy", "Haruki Murakami", 135.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216758.jpg", 13, "Một trong những kiệt tác của Murakami, Rừng Na Uy kể về mối tình tay ba đầy day dứt của chàng trai Toru giữa hai cô gái Naoko và Midori. Với bối cảnh Nhật Bản thập niên 60, cuốn sách không chỉ là câu chuyện tình yêu mà còn là hành trình khám phá nỗi cô đơn, sự mất mát và những vết thương lòng của tuổi trẻ."),
("Đồi Gió Hú", "Emily Brontë", 108.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590966.jpg", 9, "Tác phẩm kinh điển của văn học Anh kể về tình yêu mãnh liệt nhưng đầy bi kịch giữa Heathcliff và Catherine trên vùng đồng cỏ hoang dã Yorkshire. Với lối kể chuyện dữ dội và cảm xúc sâu sắc, Emily Brontë đã tạo nên một câu chuyện vừa lãng mạn vừa ám ảnh, nơi tình yêu và sự trả thù đan xen không lối thoát."),
("Người Đua Diều", "Khaled Hosseini", 115.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590973.jpg", 14, "Câu chuyện cảm động về tình bạn giữa Amir và Hassan trong bối cảnh chiến tranh Afghanistan. Qua hành trình chuộc lỗi của Amir, Khaled Hosseini khắc họa sâu sắc những giá trị về lòng trung thành, sự hy sinh và sức mạnh của tình người, khiến người đọc không thể cầm lòng trước những nỗi đau và niềm hy vọng đan xen."),
("Những Người Khốn Khổ", "Victor Hugo", 165.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590980.jpg", 17, "Tác phẩm vĩ đại của Victor Hugo kể về số phận của Jean Valjean – một người đàn ông tìm cách làm lại cuộc đời sau những năm tháng tù đày. Với bối cảnh nước Pháp thế kỷ 19 đầy bất công, cuốn sách là lời ca ngợi lòng nhân ái, sự tha thứ và khát vọng tự do, đồng thời phê phán sâu sắc những bất bình đẳng xã hội."),
("1984", "George Orwell", 98.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590997.jpg", 12, "Tiểu thuyết dystopia kinh điển miêu tả một thế giới tương lai nơi con người bị kiểm soát hoàn toàn bởi chế độ độc tài. Qua câu chuyện về Winston Smith, George Orwell cảnh báo về sự nguy hiểm của quyền lực tuyệt đối, sự thao túng sự thật và mất đi tự do cá nhân, để lại ấn tượng sâu sắc về giá trị của tự do và nhân tính."),
("Hoàng Tử Bé", "Antoine de Saint-Exupéry", 65.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216765.jpg", 18, "Một câu chuyện triết lý giản dị nhưng sâu sắc về hành trình của Hoàng tử bé từ hành tinh nhỏ của mình đến Trái Đất. Qua những cuộc gặp gỡ với các nhân vật độc đáo, tác phẩm mang đến bài học về tình yêu, дружба (tình bạn), và ý nghĩa của cuộc sống, khiến cả trẻ em lẫn người lớn đều tìm thấy sự đồng cảm."),
("Bí Mật Của Naoko", "Higashino Keigo", 120.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591000.jpg", 10, "Tiểu thuyết tâm lý ly kỳ của Higashino Keigo kể về người chồng mất vợ trong một tai nạn, nhưng linh hồn cô ấy lại sống trong cơ thể con gái. Với lối kể chuyện hấp dẫn và những tình tiết bất ngờ, cuốn sách không chỉ là một câu chuyện trinh thám mà còn là một khám phá sâu sắc về tình yêu, ký ức và sự tái sinh."),
("Ông Trăm Tuổi Trèo Qua Cửa Sổ Và Biến Mất", "Jonas Jonasson", 135.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591024.jpg", 9, "Cuộc phiêu lưu hài hước và kỳ thú của ông lão Allan Karlsson, người trốn khỏi viện dưỡng lão vào đúng ngày sinh nhật trăm tuổi. Với những tình huống dở khóc dở cười và những câu chuyện lịch sử đan xen, Jonas Jonasson mang đến một tác phẩm vừa giải trí vừa đầy ý nghĩa về sự tự do và niềm vui sống."),
("Sự Im Lặng Của Bầy Cừu", "Thomas Harris", 145.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067590942.jpg", 11, "Tiểu thuyết kinh dị tâm lý xuất sắc kể về cuộc đấu trí căng thẳng giữa nữ thực tập sinh FBI Clarice Starling và tên tội phạm ăn thịt người Hannibal Lecter. Với lối kể chuyện lôi cuốn và không khí u ám, Thomas Harris đã tạo nên một kiệt tác trinh thám khiến người đọc vừa sợ hãi vừa bị cuốn hút không thể rời mắt."),
("Bố Con Cá Gai", "Cho Chang-in", 95.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591031.jpg", 8, "Một câu chuyện cảm động về tình cha con trong bối cảnh Hàn Quốc hiện đại, nơi người cha mắc bệnh nan y tìm cách để lại những kỷ niệm đẹp cho con trai. Với giọng văn chân thành và những chi tiết giàu cảm xúc, cuốn sách là lời nhắc nhở về giá trị của gia đình và tình yêu thương vô điều kiện."),
("Tâm Lý Học Tội Phạm", "Stanton E. Samenow", 115.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540414.jpg", 15, "Cuốn sách phân tích sâu sắc tâm lý của những kẻ phạm tội, hé lộ cách suy nghĩ và hành vi khác biệt của họ so với người bình thường. Stanton E. Samenow không chỉ cung cấp cái nhìn chuyên sâu từ góc độ khoa học mà còn đặt ra những câu hỏi quan trọng về trách nhiệm cá nhân và khả năng thay đổi của con người trong xã hội."),
("Đừng Lựa Chọn An Nhàn Khi Còn Trẻ", "Cảnh Thiên", 88.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540438.jpg", 12, "Một cuốn sách truyền động lực dành cho người trẻ, khuyến khích họ dấn thân, nỗ lực và không ngừng thử thách bản thân thay vì chọn cuộc sống an nhàn. Với những câu chuyện thực tế và lời khuyên chân thành, Cảnh Thiên giúp độc giả nhận ra rằng tuổi trẻ là thời điểm để gieo mầm cho thành công lớn trong tương lai."),
("Hãy Tự Mình Thắp Đuốc Lên Mà Đi", "Trần Phi", 82.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540445.jpg", 10, "Tác phẩm khích lệ tinh thần tự lập và lòng can đảm trong cuộc sống, với thông điệp rằng mỗi người phải tự tìm ánh sáng cho con đường của mình. Qua những câu chuyện đời thường và bài học sâu sắc, Trần Phi truyền cảm hứng để độc giả vượt qua khó khăn, tin vào bản thân và không ngừng tiến về phía trước."),
("Những Tù Nhân Của Địa Lý", "Tim Marshall", 148.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591048.jpg", 13, "Cuốn sách phân tích cách địa lý định hình lịch sử, chính trị và số phận các quốc gia trên thế giới. Từ dãy núi Himalaya đến sa mạc Sahara, Tim Marshall dẫn dắt người đọc qua những câu chuyện hấp dẫn, cho thấy sức mạnh của tự nhiên không chỉ là bối cảnh mà còn là nhân tố quyết định trong sự phát triển của nhân loại."),
("Khi Hơi Thở Hóa Thinh Không", "Paul Kalanithi", 92.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216772.jpg", 16, "Hồi ký cảm động của Paul Kalanithi – một bác sĩ phẫu thuật thần kinh đối mặt với căn bệnh ung thư giai đoạn cuối. Qua từng trang sách, ông chia sẻ những suy ngẫm sâu sắc về sự sống, cái chết và ý nghĩa của việc làm người, để lại bài học nhân văn quý giá về lòng dũng cảm và tình yêu dành cho cuộc đời."),
("Cánh Đồng Bất Tận", "Nguyễn Ngọc Tư", 75.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177906.jpg", 9, "Tập truyện ngắn khắc họa cuộc sống miền Tây sông nước với những số phận éo le nhưng đầy sức sống. Nguyễn Ngọc Tư dùng ngòi bút trữ tình và chân thực để kể về những con người nhỏ bé trong xã hội, nơi tình yêu, nỗi đau và hy vọng đan xen, tạo nên một bức tranh đậm chất nhân văn và giàu cảm xúc."),
("Tuổi Trẻ Đáng Giá Bao Nhiêu", "Rosie Nguyễn", 86.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936066709147.jpg", 14, "Một cuốn sách truyền cảm hứng dành cho người trẻ, kết hợp giữa trải nghiệm cá nhân của tác giả và những lời khuyên thiết thực về học tập, du lịch và định hướng cuộc đời. Rosie Nguyễn khuyến khích độc giả sống hết mình, khám phá bản thân và không ngừng nỗ lực để tuổi trẻ trở thành quãng thời gian đáng giá nhất."),
("Chuyện Phiêu Lưu Của Huckleberry Finn", "Mark Twain", 82.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591055.jpg", 11, "Cuộc phiêu lưu của cậu bé Huck Finn trên dòng sông Mississippi là một câu chuyện vừa hài hước vừa cảm động về tự do và tình bạn. Với giọng văn dí dỏm và sâu sắc, Mark Twain không chỉ tái hiện nước Mỹ thế kỷ 19 mà còn phê phán những bất công xã hội, để lại dấu ấn về lòng nhân ái và tinh thần phản kháng."),
("Dạy Con Làm Giàu - Tập 1", "Robert Kiyosaki", 108.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848551.jpg", 17, "Phần đầu tiên trong loạt sách nổi tiếng của Robert Kiyosaki, cuốn sách giới thiệu khái niệm về giáo dục tài chính qua câu chuyện của hai người cha với hai cách tư duy khác nhau. Với lối kể chuyện dễ hiểu và những bài học thực tế, tác phẩm giúp người đọc thay đổi cách nhìn về tiền bạc và xây dựng tư duy làm giàu từ sớm."),
("Cô Gái Có Hình Xăm Rồng", "Stieg Larsson", 145.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591062.jpg", 12, "Tiểu thuyết trinh thám kịch tính kể về hacker Lisbeth Salander và nhà báo Mikael Blomkvist trong hành trình điều tra một vụ mất tích bí ẩn. Với những tình tiết gay cấn, nhân vật độc đáo và không khí Bắc Âu lạnh lẽo, Stieg Larsson đã tạo nên một tác phẩm vừa hấp dẫn vừa sâu sắc, lôi cuốn người đọc đến trang cuối cùng."),
("Hiệu Ứng Chim Mồi", "Jonah Berger", 99.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540452.jpg", 10, "Cuốn sách khám phá tâm lý học hành vi qua những chiến lược ảnh hưởng đến quyết định của con người trong kinh doanh và cuộc sống. Jonah Berger phân tích cách các yếu tố nhỏ bé như “chim mồi” có thể thay đổi cách chúng ta lựa chọn, mang đến cái nhìn thú vị và thực tiễn về cách vận dụng tâm lý để đạt được mục tiêu."),
("Bảy Bước Tới Mùa Hè", "Nguyễn Nhật Ánh", 95.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177913.jpg", 15, "Một câu chuyện mùa hè trong trẻo và ngọt ngào của Nguyễn Nhật Ánh, nơi những kỷ niệm tuổi học trò được tái hiện qua tình bạn, tình yêu đầu đời và những trò nghịch ngợm đáng nhớ. Với văn phong nhẹ nhàng, cuốn sách mang đến cảm giác bình yên và gợi nhớ về một thời áo trắng đã qua, khiến người đọc không khỏi bồi hồi."),
("Truyện Kiều", "Nguyễn Du", 60.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177920.jpg", 18, "Tác phẩm thơ kinh điển của văn học Việt Nam, Truyện Kiều kể về cuộc đời đầy bi kịch của Thúy Kiều – một người con gái tài sắc vẹn toàn nhưng phải chịu nhiều bất hạnh. Với ngôn ngữ tuyệt đẹp và những câu thơ giàu cảm xúc, Nguyễn Du không chỉ khắc họa số phận con người mà còn gửi gắm những triết lý sâu sắc về nhân sinh."),
("Đời Ngắn Đừng Ngủ Dài", "Robin Sharma", 78.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848568.jpg", 13, "Cuốn sách truyền động lực của Robin Sharma là lời nhắc nhở rằng cuộc đời ngắn ngủi, và chúng ta cần sống hết mình mỗi ngày. Qua những câu chuyện ngắn và bài học thực tế, tác giả khuyến khích người đọc trân trọng thời gian, đặt mục tiêu lớn và hành động để biến mỗi khoảnh khắc thành ý nghĩa, thay vì để nó trôi qua vô ích."),
("Thiên Thần Nhỏ Của Tôi", "Nguyễn Nhật Ánh", 85.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177937.jpg", 11, "Một câu chuyện tuổi thơ dịu dàng và trong sáng của Nguyễn Nhật Ánh, nơi tình cảm gia đình và những rung động đầu đời được khắc họa tinh tế. Tác phẩm đưa người đọc trở về những ngày tháng hồn nhiên, nơi tình yêu thương của cha mẹ và sự ngây ngô của trẻ thơ tạo nên một thế giới đầy ấm áp và xúc động."),
("Người Trong Gương", "Higashino Keigo", 110.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591079.jpg", 9, "Tiểu thuyết trinh thám hấp dẫn của Higashino Keigo kể về một vụ án bí ẩn với những manh mối dẫn đến những bí mật sâu kín trong tâm hồn con người. Với lối kể chuyện lôi cuốn và những cú twist bất ngờ, cuốn sách không chỉ là một câu chuyện phá án mà còn là một hành trình khám phá bản chất thật sự của mỗi cá nhân."),
("Cậu Bé Rừng Xanh", "Rudyard Kipling", 72.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591086.jpg", 16, "Cuộc phiêu lưu kỳ thú của Mowgli – cậu bé được nuôi dưỡng bởi bầy sói trong rừng sâu Ấn Độ. Qua những thử thách với hổ Shere Khan và tình bạn với gấu Baloo, Rudyard Kipling mang đến một câu chuyện đầy màu sắc, không chỉ giải trí mà còn truyền tải bài học về lòng dũng cảm, tình người và sự hòa hợp với thiên nhiên."),
("Hành Trình Về Phương Đông", "Baird T. Spalding", 98.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848575.jpg", 14, "Cuốn sách kể về chuyến đi của một đoàn nghiên cứu phương Tây đến Ấn Độ và Tây Tạng để khám phá những bí ẩn tâm linh. Với những câu chuyện về các bậc thầy yoga, thiền định và triết lý sống, Baird T. Spalding mở ra một thế giới huyền bí, khơi dậy sự tò mò và cảm hứng về ý nghĩa sâu xa của cuộc đời."),
("Còn Chút Gì Để Nhớ", "Nguyễn Nhật Ánh", 80.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177944.jpg", 12, "Hồi ức tuổi trẻ trong sáng và nhẹ nhàng của Nguyễn Nhật Ánh, kể về những ngày tháng đầu tiên xa nhà của cậu học trò Chương. Với những rung động đầu đời, tình bạn chân thành và nỗi nhớ quê hương, cuốn sách như một bản nhạc dịu dàng, gợi lên những cảm xúc bâng khuâng về một thời đã qua không thể trở lại."),
("Đi Tìm Lẽ Sống", "Viktor E. Frankl", 88.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216789.jpg", 17, "Hồi ký triết lý sâu sắc của Viktor E. Frankl, một bác sĩ tâm lý sống sót qua trại tập trung Nazi. Từ những trải nghiệm đau thương, ông xây dựng học thuyết về ý nghĩa cuộc sống, khẳng định rằng ngay cả trong nghịch cảnh, con người vẫn có thể tìm thấy lý do để sống và hy vọng, khiến cuốn sách trở thành nguồn cảm hứng bất tận."),
("Bí Mật Dưới Đáy Biển", "Jules Verne", 95.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591093.jpg", 10, "Cuốn tiểu thuyết phiêu lưu kinh điển của Jules Verne kể về hành trình khám phá đại dương của giáo sư Aronnax cùng thuyền trưởng Nemo trên con tàu Nautilus. Với trí tưởng tượng phong phú và những mô tả sống động, tác phẩm đưa người đọc vào một thế giới dưới nước đầy kỳ bí, nơi khoa học và phiêu lưu hòa quyện tuyệt vời."),
("Những Ngọn Gió Hua Tát", "Nguyễn Ngọc Tư", 78.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177951.jpg", 13, "Tập truyện ngắn đậm chất miền Tây của Nguyễn Ngọc Tư, nơi những con người bình dị sống giữa vùng đất khắc nghiệt kể lại câu chuyện của mình. Với giọng văn trữ tình và sâu lắng, tác phẩm khắc họa những nỗi đau, niềm vui và khát vọng sống mãnh liệt, để lại dư âm về tình người và sức mạnh của sự kiên cường."),
("Hạt Giống Tâm Hồn - Tập 1", "Nhiều Tác Giả", 65.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935086848582.jpg", 19, "Tập hợp những câu chuyện ngắn cảm động về tình yêu, tình bạn và những giá trị tốt đẹp trong cuộc sống, Hạt Giống Tâm Hồn là nguồn cảm hứng để nuôi dưỡng tâm hồn. Mỗi câu chuyện như một hạt giống nhỏ, gieo vào lòng người đọc sự lạc quan, lòng trắc ẩn và niềm tin vào điều kỳ diệu của cuộc đời."),
("Nhật Ký Đặng Thùy Trâm", "Đặng Thùy Trâm", 82.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177968.jpg", 11, "Hồi ký xúc động của nữ bác sĩ Đặng Thùy Trâm, người hy sinh trong chiến tranh Việt Nam, ghi lại những ngày tháng gian khó nhưng đầy lý tưởng. Qua từng trang nhật ký, người đọc cảm nhận được lòng yêu nước, sự hy sinh thầm lặng và những cảm xúc chân thật của một trái tim trẻ tuổi giữa khói lửa chiến tranh."),
("Harry Potter Và Phòng Chứa Bí Mật", "J.K. Rowling", 155.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177975.jpg", 18, "Phần hai trong loạt truyện Harry Potter tiếp tục hành trình phép thuật của cậu bé phù thủy tại trường Hogwarts. Với những bí ẩn trong Phòng Chứa Bí Mật và cuộc đối đầu với kẻ thù mới, J.K. Rowling mang đến một câu chuyện kịch tính, đầy bất ngờ, đồng thời khẳng định sức mạnh của tình bạn và lòng dũng cảm."),
("Người Lạ Trong Nhà", "Shari Lapena", 115.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591109.jpg", 9, "Tiểu thuyết giật gân kể về một vụ tai nạn bí ẩn khiến người vợ mất trí nhớ, kéo theo hàng loạt bí mật đen tối trong gia đình dần hé lộ. Với lối kể chuyện cuốn hút và những tình tiết bất ngờ, Shari Lapena tạo nên một câu chuyện căng thẳng, nơi sự thật ẩn giấu khiến người đọc không thể rời mắt."),
("Chuyện Tình Ở Paris", "Marc Levy", 108.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8935235216796.jpg", 12, "Câu chuyện tình lãng mạn giữa lòng thành phố Paris hoa lệ, nơi hai con người xa lạ tìm thấy nhau trong những khoảnh khắc bất ngờ của số phận. Marc Levy dùng ngòi bút tinh tế để kể về tình yêu, sự mất mát và hy vọng, tạo nên một tác phẩm vừa ngọt ngào vừa sâu lắng, khiến người đọc mơ về một mối tình đẹp như cổ tích."),
("Bí Ẩn Dưới Lòng Đất", "James Rollins", 135.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591116.jpg", 15, "Cuốn tiểu thuyết phiêu lưu ly kỳ kể về một nhóm nhà khoa học khám phá những bí ẩn cổ xưa trong hang động dưới lòng đất. Với nhịp điệu nhanh, những tình tiết gay cấn và kiến thức khoa học phong phú, James Rollins mang đến một hành trình đầy kịch tính, nơi con người đối mặt với những hiểm nguy và bí mật vượt ngoài tưởng tượng."),
("Tuổi Thơ Dữ Dội", "Phùng Quán", 145.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177982.jpg", 20, "Tác phẩm cảm động về những đứa trẻ tham gia kháng chiến chống Pháp, nơi tuổi thơ trong sáng bị cuốn vào khói lửa chiến tranh. Phùng Quán khắc họa sống động lòng yêu nước, sự hy sinh và tình đồng đội của các em, tạo nên một bức tranh vừa bi hùng vừa xúc động về thế hệ trẻ trong lịch sử Việt Nam."),
("Ngàn Mặt Trời Rực Rỡ", "Khaled Hosseini", 125.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591123.jpg", 10, "Câu chuyện về hai người phụ nữ Afghanistan – Mariam và Laila – trong bối cảnh chiến tranh và áp bức. Qua ngòi bút của Khaled Hosseini, tác phẩm không chỉ kể về nỗi đau mà còn tôn vinh sức mạnh, sự kiên cường và tình yêu của phụ nữ, để lại dấu ấn sâu đậm về lòng trắc ẩn và hy vọng giữa nghịch cảnh."),
("Từng Có Người Yêu Tôi Như Sinh Mệnh", "Thư Nghi", 89.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936186540469.jpg", 13, "Tiểu thuyết tình yêu day dứt kể về mối tình sâu đậm nhưng đầy bi kịch giữa cô gái và chàng trai sẵn sàng hy sinh tất cả vì cô. Với giọng văn giàu cảm xúc, Thư Nghi đưa người đọc vào một câu chuyện vừa ngọt ngào vừa đau thương, nơi tình yêu trở thành ánh sáng duy nhất giữa bóng tối của số phận."),
("Thời Thơ Ấu", "Maxim Gorky", 78.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591130.jpg", 16, "Hồi ký chân thực của Maxim Gorky về tuổi thơ nghèo khó và khắc nghiệt ở nước Nga cuối thế kỷ 19. Qua những trang sách, ông kể lại những ngày tháng sống với ông bà, những nỗi đau và niềm vui nhỏ bé, để lại bài học về sự kiên cường và khát vọng vươn lên từ hoàn cảnh nghiệt ngã."),
("Đừng Để Mẹ Khóc", "Shin Kyung-sook", 95.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591147.jpg", 11, "Câu chuyện cảm động về tình mẫu tử, kể về hành trình của các con đi tìm người mẹ mất tích ở Seoul. Shin Kyung-sook dùng ngòi bút tinh tế để tái hiện những hy sinh thầm lặng của mẹ, những điều chưa kịp nói và nỗi ân hận của con cái, khiến người đọc rơi nước mắt trước tình yêu vô bờ của gia đình."),
("Người Bán Hạnh Phúc", "Nguyễn Nhật Ánh", 92.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8934974177999.jpg", 14, "Tác phẩm ấm áp của Nguyễn Nhật Ánh kể về hành trình của một người đàn ông mang hạnh phúc đến cho người khác qua những điều giản dị. Với văn phong trong sáng và những chi tiết đầy cảm xúc, cuốn sách là lời nhắc nhở về giá trị của niềm vui, lòng tốt và sự kết nối giữa con người trong cuộc sống."),
("Trò Chơi Vương Quyền - Tập 1", "George R.R. Martin", 185.00, "https://cdn0.fahasa.com/media/catalog/product/8/9/8936067591154.jpg", 17, "Phần đầu tiên của bộ tiểu thuyết sử thi nổi tiếng, kể về cuộc tranh giành ngai vàng giữa các gia tộc quyền lực ở Westeros. Với cốt truyện phức tạp, nhân vật đa chiều và những tình tiết bất ngờ, George R.R. Martin đã tạo nên một thế giới giả tưởng đầy kịch tính, nơi lòng trung thành, sự phản bội và tham vọng đan xen không ngừng.");

SELECT * FROM Books;
SELECT * FROM Orders;
SELECT * FROM Order_Details;
SELECT * FROM Users;
SELECT * FROM Roles;

SELECT * FROM books WHERE price BETWEEN 50 AND 100;


